### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by jaichhabra**
added bullet pointers

### CODE REVIEW

**Comment by joho** [comment]
This is a very helpful idea thank you! Keen to merge if it works, but it doesn't look like it does.

image

If you can get the contents back as bullet points, and make it work with a space between the number and the first word of the headings, then I'll merge ASAP.

**Comment by jaichhabra** [comment]
okay sure. I'll do it

**Comment by jaichhabra** [comment]
i've done some changes

**Comment by joho** [comment]
Respectfully @jaichhabra it wasn't super helpful to open a second PR with #56, and even then it didn't address my requested changes.

Also on my first scan I thought this was something related to the new TOC changes github announced in https://twitter.com/github/status/1376636651963842562 but it seems like that was already working and best case this was a small cosmetic change I didn't need.

Closing both PRs, please don't open another along these lines.

**Pull request closed without merging**
